### ISSUE TITLE
Installation instructions are weird? 

### ISSUE THREAD

**Issue by 0xinit** [pkkid/x11pygrid#42]
It might be a dumb question, but I think the installation instructions are bit misguided.

git clone https://github.com/pkkid/x11pygrid.git --- this clones the x11pygrid folder/repo. The repo doesn't contain pygrid folder and ./pygrid file as mentioned in the next stap -> cd pygrid && ./pygrid.py

then, if I use "make" it doesn't build dist or build folder and I need to explicitly type "python3 setup.py sdist bdist_wheel"

After doing that, the folders are built but running ./x11pygrid or "python3 x11pygrid" gives me this error:

Traceback (most recent call last):
  File "/home/gaurav/x11pygrid/src/x11pygrid/x11pygrid.py", line 13, in <module>
    import single_process.init  # noqa
ModuleNotFoundError: No module named 'single_process'

Can anyone help me with this? And what I am doing wrong?

Thanks!

**Comment by SP5D** [comment]
I'm right now (literally, vscode is opened!) fixing README.

Do you have pip? Or (even better) pipx?

**Comment by SP5D** [comment]
Ok, I'll assume that you have it.
If so,
```pip install --user x11pygrid```
should work without problem.

**Comment by SP5D** [comment]
@Gauravajariwal11 
I've upgraded installation instructions. https://github.com/pkkid/x11pygrid/blob/master/README.md#installation
I hope it helped, but you're welcome to ask if there is anything unclear!

**Comment by Gauravajariwal11** [comment]
I went to bed straight after opening this issue, and didn't see it until now. 

yea, I got pip and pipx, didnt know i can use those to install it.
Also great work in updating the instructions! Those were the steps I was gonna do, and pull a request to edit README, but thought I might do some wrong so opened an issue instead!

**Comment by SP5D** [comment]
> "didnt know i can use those"
You have pretty good excuse for that – it's packed and uploaded to PyPi since the very last week ;) README was a bit behind.

Doing my best, thanks!
